### ISSUE TITLE
libcudart.so error

### ISSUE THREAD

**Issue by fisakhan** [ascust/3DMM-Fitting-Pytorch#5]
While executing python3 fit.py --img data/000002.jpg, I receive the following error. The installed version of cuda on my system is 11. What should I do?

```
Traceback (most recent call last):
  File "fit.py", line 6, in <module>
    from core.models import ReconModel
  File "/home/tface/Projects/torch/3DMM-Fitting-Pytorch/core/models.py", line 5, in <module>
    from pytorch3d.renderer import (
  File "/home/tface/.virtualenvs/torch/lib/python3.6/site-packages/pytorch3d/renderer/__init__.py", line 3, in <module>
    from .blending import (
  File "/home/tface/.virtualenvs/torch/lib/python3.6/site-packages/pytorch3d/renderer/blending.py", line 9, in <module>
    from pytorch3d import _C
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory


$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0


```

**Comment by fisakhan** [comment]
The problem was with the installation of pytorch3d. I removed pytorched and reinstalled it using https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md#building--installing-from-source 
Problem solved
